language: r
cache: packages
pandoc_version: 2.10.1
before_script:
- chmod +x ./_build.sh
- chmod +x ./_deploy.sh

script:
- "./_build.sh"
- "./_deploy.sh"
env:
  global:
    secure: rfGyPKPYg+InfFQngOtRAJNZCNow2jnNPbmEwbyvkRj9Y9WfIUZbvmPodZ8ntF/JGlaKGu5tG8+tEsFN9/lxzctLTJ+LM8jOS2o48CSYpScvBWy5QVYPxmRXSA0TBaPQk2hk/RtncMFuEIqIhaFPFB1mrPDjxuLsT7VSwlwqaj7qDgL/FCWRGIrrRYNEIL4BC/HqnLxEvuU5YOte/JVTHzhq/W68Kf9EFs2LhcgUFAM+BFeP+Ej4kDKH5FTGusfMhMwg+KM3xzTLLdcG6pxdh3jrOuEuO2RMcGdKahI5pH8hNALUUtB56L97wdY1RkgBLwICJtTV3Py8UaBcdKUEGPxWKvWXbjm6R3mm3VbXgob1jai2qohVpTkPsJoS9eKBvPm3Tak8BKRGeqO94MfBSnl/jwV/jXJOSn69Nm2qMO+kQHcmYBu66WnzUbOA+kreAR6tKgvUB6sfmjGVJKNYxO53DYaFZBacVIrryWc7mX5G7PCTV2ShQNxBvP8fUZrG+uhprKDTHeilJbrMx1Oj/fXNPVRxILWOLOAihTHI5bsxLgK4XtCquPt+8MD3mcBYKsOLn8k/11Yc72b4Utgu+wexqt1h7Vgk+MLTLTetRa7KxKpDGSZTpH6x1uXjc5XrpPjM469oXVsKZUYkj1AA+ObnHsVXjitpH69nJ9cNRv0=
